services:
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build: ./server
        image: docker.io/ektasuman/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #Worker Service
    worker:
        build: ./worker
        image: docker.io/ektasuman/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #React client        
    client:
        build: ./client
        image: docker.io/ektasuman/complex-client
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: ./nginx
        ports:
            - '3050:80'
